# Generated by Django 4.2.6 on 2023-11-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rep',
            field=models.IntegerField(choices=[(1, 'Oui'), (2, 'Non')], default=1),
        ),
    ]
