# Generated by Django 4.2.6 on 2023-11-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_choice_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='rep',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.IntegerField(choices=[(1, 'Oui'), (2, 'Non')], default=1),
        ),
    ]
